language: php
php:
    - '5.5'
    - '5.6'
    - '5.7'
    - '7.0'

services:
    - mysql

before_script:
    - composer install
    - mysql -e 'create database dsql_test;'

after_script:
    - vendor/bin/test-reporter

script:
    - phpunit
    - phpunit --configuration phpunit-mysql.xml

notifications:
    slack:
        rooms:
            - agiletoolkit:bjrKuPBf1h4cYiNxPBQ1kF6c#dsql
        on_success: change
    email: false

